server:
  port: 9090
spring:
  profiles:
    active: local
    include:
      - domain
      - swagger
      - market
  session:
    store-type: jdbc
  datasource:
    data: classpath:schema/session.sql
