server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
spring:
  session:
    store-type: jdbc
  profiles:
    active: local
    include:
      - domain
      - swagger
      - market
      - rds
