coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        flags:
          - unit
        paths:
          - "src"
        if_ci_failed: success
        informational: true
        only_pulls: true
