FROM adoptopenjdk/openjdk11:alpine-slim AS BUILD
ENV APP_HOME=/usr/app
WORKDIR $APP_HOME
COPY . $APP_HOME
RUN ./gradlew clean :muyaho-batch:bootJar

FROM adoptopenjdk/openjdk11:alpine-jre
ENV APP_HOME=/usr/app
COPY --from=BUILD  $APP_HOME/muyaho-batch/build/libs/muyaho-batch.jar /muyaho-batch.jar
