spring:
  jpa:
    properties:
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.dialect.storage_engine: innodb
      hibernate.default_batch_fetch_size: 1000
      hibernate.query.in_clause_parameter_padding: true
      hibernate.connection.provider_disables_autocommit: true
    open-in-view: false
  datasource:
    hikari:
      auto-commit: false
---
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:muyaho;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
    data: classpath:schema/session.sql

---
spring:
  profiles: local-will
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/muyaho
      username: root
      password: '0212'
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
