spring:
  profiles: dev, local
bitcoin:
  upbit:
    markets:
      url: https://api.upbit.com/v1/market/all
    trade:
      url: https://api.upbit.com/v1/ticker
stock:
  markets:
    url: http://muyaho-api-alb-302156047.ap-northeast-2.elb.amazonaws.com:5000/api/v1/stock/code
  trade:
    url: http://muyaho-api-alb-302156047.ap-northeast-2.elb.amazonaws.com:5000/api/v1/stock/price
currency:
  exchange:
    url: https://earthquake.kr:23490/query/USDKRW

---
spring:
  profiles:
