spring:
  profiles:
    active: local
    include:
      - domain
      - market
  batch:
    job:
      names: ${job.name:NONE}
  main:
    web-application-type: none
logging:
  level:
    org.springframework.batch: DEBUG
