# 새로운 소유한 주식을 등록한다
POST {{api}}/api/v1/member/stock
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "stockId": 1,
    "purchasePrice": 10000000,
    "quantity": 3,
    "currencyType": "WON",
    "purchaseTotalPrice": 1000
}

### 내 주식 정보를 가져오는 API
GET {{api}}/api/v1/member/stock/status
Authorization: Bearer {{AUTHORIZATION}}

### 내가 마지막으로 주식 정보를 가져오는 API
GET {{api}}/api/v1/member/stock/status/previous
Authorization: Bearer {{AUTHORIZATION}}


### 내가 소유한 주식 리스트를 조회한다
GET {{api}}/api/v1/member/stock?type=BITCOIN
Authorization: Bearer {{AUTHORIZATION}}

### 내가 소유한 주식을 수정한다
PUT {{api}}/api/v1/member/stock
Content-Type: application/json
Authorization: Bearer {{AUTHORIZATION}}

{
    "memberStockId": 1,
    "purchasePrice": 2000,
    "quantity": 500,
    "currencyType": "DOLLAR",
    "purchaseTotalPrice": 130000
}

### 내가 소유한 주식을 삭제한다
DELETE {{api}}/api/v1/member/stock?memberStockId=1
Authorization: Bearer {{AUTHORIZATION}}
