name: 개발환경 API 서버 배포

on:
  push:
    branches:
      - develop
      - feature/55
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout@v2
        uses: actions/checkout@v2

      - name: Setup Secret Properties
        env:
          PROFILES: dev
          DB_URI: ${{secrets.JDBC_URI}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_DRIVER: ${{secrets.DB_DRIVER}}

          RESOURCE_PWD: muyaho-domain/src/main/resources
        run: |
          echo -e "spring.profiles=$PROFILES\nspring.datasource.hikari.jdbc-url=$DB_URI\nspring.datasource.hikari.username=$DB_USERNAME\nspring.datasource.hikari.password=$DB_PASSWORD\nspring.datasource.hikari.driver-class-name=$DB_DRIVER" > $RESOURCE_PWD/application-rds.properties

      - name: Get dev version
        id: dev-version
        run: |
          VERSION=`cat ./version.txt`-${{ github.run_id }}
          echo "::set-output name=version::$VERSION"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push muyaho-api
        id: build-api
        env:
          DOCKER_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DOCKER_REPOSITORY: muyaho-api
          IMAGE_TAG: ${{ steps.dev-version.outputs.version }}
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"

      - name: Download muyaho-api task definition
        id: download-task-definition
        run: |
          aws ecs describe-task-definition --task-definition muyaho-api-task --query taskDefinition > task-definition-dev.json
          echo "::set-output name=task-definition::$GITHUB_WORKSPACE/task-definition-dev.json"

      - name: Render Amazon ECS muyaho-api task definition
        id: render-api-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.download-task-definition.outputs.task-definition }}
          container-name: muyaho-api
          image: ${{ steps.build-api.outputs.image }}

      - name: Deploy muyaho-api to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-api-container.outputs.task-definition }}
          cluster: muyaho-api
          service: muyaho-api-dev
          wait-for-service-stability: true
